FROM node:14-alpine

WORKDIR /app

# In case of CMD the command provided in docker run will override the command provided in CMD.
# In case of ENTRYPOINT the command provided in docker run will be appended to the command provided in ENTRYPOINT.
ENTRYPOINT [ "npm" ]