docker-compose-up:
	docker-compose up

docker-compose-down:
	docker-compose down

docker-compose-up-detached:
	docker-compose up -d

dokcer-compose-up-with-build:
	docker-compose up --build

dokcer-compose-build:
	docker-compose build

docker-compose-down-volumes:
	docker-compose down -v