apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: shah20/story:2
          volumeMounts:
            - name: story-volume
              mountPath: /app/story
      volumes:
        - name: story-volume
          # Creates an empty directory and provides it to the container
          # The directory is created inside the container at: /app/story
          # Each container in the pod will have its own empty directory
          # Each replica will have its own empty directory
          # emptyDir: {}
          # -----------------
          # Creates a folder on host machine and provides it to the container
          # Shared by all containers in the pod
          # If directory on hostmaching has data, it will be available to the container
          # hostPath:
          #   path: /data
          #   type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: host-pvc