apiVersion: v1
kind: Service
metadata:
  name: users-service # kubernetes create env variable and pass it to all containers, whose value is IP address of the service
  # as <service_name>_SERVICE_HOST with service_name as every letter in caps and - replaced by _
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080